remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Ifenia
description: Gérez vos voyages en toute simplicité

# Personnalisation des couleurs
colors:
  header-bg: "#CD5C5C"    # Rouge saumon foncé (Indian Red)
  header-text: "#FFFFFF"   # Texte blanc pour le contraste
  link: "#CD5C5C"          # Liens en rouge saumon
  btn-primary-bg: "#CD5C5C"
  btn-primary-text: "#FFFFFF"

# Style personnalisé
style: |
  .page-header {
    background-color: #CD5C5C !important;
    background-image: linear-gradient(120deg, #CD5C5C, #A04040) !important;
    padding: 2rem 1rem;
  }
  .main-content h1, .main-content h2, .main-content h3, .main-content h4, .main-content h5, .main-content h6 {
    color: #CD5C5C !important;
  }
  .main-content a {
    color: #CD5C5C !important;
  }
  .btn {
    background-color: #CD5C5C !important;
    color: white !important;
    margin-right: 5px;
  }
  .main-nav {
    margin-top: 1rem;
  }
  .store-badges {
    display: flex;
    flex-wrap: wrap;
    gap: 20px;
    margin-top: 2rem;
  }
  .screenshot-gallery {
    display: flex;
    flex-wrap: wrap;
    gap: 15px;
    justify-content: center;
    margin: 2rem 0;
  }
  .screenshot-gallery img {
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0,0,0,0.1);
  }
